# 日志配置
logger:
  level: "error"           # 日志级别: debug, info, warn, error, dpanic, panic, fatal
  console: true           # 是否输出到控制台
  file_path: "logs/ai-rss.log" # 日志文件路径
  max_size: 50            # 单个日志文件最大大小，单位MB
  max_backups: 5          # 最多保留的旧日志文件数量
  max_age: 28             # 保留日志文件的最大天数
  compress: true          # 是否压缩旧日志文件

# Deepseek API配置
deepseek:
  api_key: "sk-************"
  model: "deepseek-chat"
  max_tokens: 8000
  max_calls: 300    # API最大调用次数，超过此次数将直接返回原始数据
  api_url: "https://api.deepseek.com/v1/chat/completions"   # API接口地址
  read_timeout: 300        # API响应读取超时时间（秒）
  api_timeout: 120         # API请求超时时间（秒）

# 输出配置
output:
  format: "markdown"
  include_metadata: true

# RSS获取配置
rss:
  days_back: 3            # 获取几天内的文章，默认为3天
  opml_file: "example.opml"  # OPML文件路径
  timeout: 20            # RSS源获取超时时间（秒），默认为20秒
  concurrency: 3         # 从10降低到3，减少并发压力
  max_retries: 3         # 最大重试次数，默认为3
  response_timeout: 300  # 从120秒增加到300秒，给API响应更多时间
  overall_timeout: 400   # 从160秒增加到400秒，整体超时时间
  retry_backoff_base: 2  # 从1秒增加到2秒，重试间隔更长

# 数据库配置
database:
  enabled: true           # 是否启用数据库存储
  file_path: "data/articles.db"  # 数据库文件路径
